SS-Soon-Senior/HanaroWa-FE

hanarowa/public/svg/ic-headerArrow.svg, hanarowa/src/app/(home)/page.tsx, hanarowa/src/app/component/page.tsx, hanarowa/src/assets/svg/IcHeaderArrow.tsx, hanarowa/src/assets/svg/index.tsx, hanarowa/src/components/atoms/Header.tsx, hanarowa/src/components/atoms/index.ts, hanarowa/tsconfig.json
=> Feat: Header component

hanarowa/package.json, hanarowa/pnpm-lock.yaml, hanarowa/src/components/atoms/StatusTab.tsx
탭바 만들었어요
```
const Tabs = [
{ key: 'facility', label: '시설' },
{ key: 'counseling', label: '상담' },
];
```
label 에 버튼에 들어갈 text 넣어서 쓰세요
=> Feat: 탭바 아톰 컴포넌트 생성

hanarowa/src/app/lesson/page.tsx
일단 강좌 목록들 더미데이터로 넣어서 뿌려놓게 만들었습니다! 추후 수정 필요.......
=> Feat:강좌 목록 페이지 생성

hanarowa/src/app/mypage/updateinfo/page.tsx
마이페이지 회원정보 수정 페이지 생성했습니다.
현재 생년월일을 6자리로 받고 있는데 이걸 그대로 갈지 말지...
=> feat: 회원정보 수정

hanarowa/src/app/mypage/page.tsx, hanarowa/src/components/atoms/inputs/InputUnderline.tsx, hanarowa/src/components/atoms/modals/Modal.tsx
글자크기 18 -> 22로 변경
회원탈퇴 클릭시 모달 띄워집니다.
=> fix:글자크기 변경 및 회원탈퇴 모달

hanarowa/pnpm-lock.yaml
=> fix: pnpm-lock.yml

hanarowa/src/apis/facility/useGetFacilityDetail.ts, hanarowa/src/app/facility/[facilityId]/page.tsx, hanarowa/src/components/facility/FacilityImageCarousel.tsx, hanarowa/src/utils/facility.ts
facility detail page get api 연동
이미지는 아직입니다.
=> Feat: facilitypage api 연동

hanarowa/src/apis/auth/postRefreshToken.ts, hanarowa/src/apis/authMiddleware.ts
=> Fix: refresh 토큰 쿠키에 저장

hanarowa/src/apis/index.ts, hanarowa/src/apis/lesson/getLessons.ts, hanarowa/src/apis/lesson/getManageLessons.ts, hanarowa/src/apis/lesson/index.ts, hanarowa/src/apis/lesson/updateLessonState.ts, hanarowa/src/app/admin/(home)/page.tsx, hanarowa/src/app/admin/lesson/manage/page.tsx, hanarowa/src/app/admin/lesson/page.tsx, hanarowa/src/app/lesson/create/page.tsx, hanarowa/src/components/atoms/tags/AdminStatusTag.tsx, hanarowa/src/components/lesson/AdminLessonCard.tsx, hanarowa/src/components/lesson/AdminManageCard.tsx, hanarowa/src/types/api.ts
=> Feat: AdminLesson

hanarowa/src/apis/member/index.ts, hanarowa/src/apis/member/usePatchMember.ts, hanarowa/src/app/auth/signup/action.ts, hanarowa/src/app/auth/signup/page.tsx, hanarowa/src/app/mypage/info/page.tsx, hanarowa/src/components/atoms/DatePicker.tsx, hanarowa/src/types/api.ts
1. 회원정보 수정 관련 API 경로 수정
2. auth/signup 페이지 대폭 수정
3. DatePicker 컴포넌트 수정
=> Fix:회원정보 수정 관련 API 수정 및 auth/signup 페이지 대폭 수정

hanarowa/src/apis/lesson/getLessonDetail.ts, hanarowa/src/apis/lesson/index.ts, hanarowa/src/apis/lesson/updateLesson.ts, hanarowa/src/app/admin/lesson/manage/[id]/page.tsx, hanarowa/src/app/admin/lesson/manage/page.tsx, hanarowa/src/app/lesson/create/page.tsx, hanarowa/src/components/atoms/DatePicker.tsx, hanarowa/src/components/atoms/tags/AdminStatusTag.tsx, hanarowa/src/components/lesson/AdminManageCard.tsx, hanarowa/src/hooks/useLessonEdit.ts, hanarowa/src/types/lesson.ts
=> Feat: Admin Lesson Detail

hanarowa/src/apis/authMiddleware.ts, hanarowa/src/apis/member/admin/useAdminGet.ts, hanarowa/src/apis/member/index.ts, hanarowa/src/app/admin/(home)/page.tsx, hanarowa/src/app/admin/member/page.tsx, hanarowa/src/app/auth/login/page.tsx, hanarowa/src/app/provider.tsx, hanarowa/src/components/atoms/MemberCard.tsx, hanarowa/src/types/api.ts
1. /admin/member 연동 (관리자 아닐 시 /auth/login 으로 감)
2. 관리자 아닐 시 /(home)/admin 못 들어가게 막음
=> Feat:관리자 회원목록 API 연동

hanarowa/src/app/facility/[facilityId]/page.tsx, hanarowa/src/app/reservation/lesson/page.tsx, hanarowa/src/components/lesson/LessonReservationCard.tsx
=> Fix : 버튼 중복클릭 방지

hanarowa/src/apis/facility/getMyFacility.ts, hanarowa/src/apis/facility/index.ts, hanarowa/src/apis/facility/useDeleteMyFacilityReservation.ts, hanarowa/src/apis/facility/useGetMyFacility.ts, hanarowa/src/app/reservation/facility/page.tsx, hanarowa/src/components/facility/RoomReservationCard.tsx, hanarowa/src/types/api.ts
내 시설 예약 내역 & 취소하기 추가 (feat. 영균)
=> Feat: facility reservation list

hanarowa/src/apis/facility/getFacilities.ts, hanarowa/src/apis/facility/index.ts, hanarowa/src/apis/facility/useGetFacilities.ts
=> Fix: 시설 목록 조회 api 수정

hanarowa/src/app/admin/facility/page.tsx, hanarowa/src/app/reservation/facility/page.tsx, hanarowa/src/components/facility/RoomReservationCard.tsx
1. 관리자의 시설 예약 취소 API 연동
2. RoomReservationCard 컴포넌트 수정하고 이 컴포넌트를 쓰는 페이지들 친절하게 다 수정해드렸습니다^^
=> Fix:RoomReservationCard 컴포넌트 수정

hanarowa/src/app/mypage/info/page.tsx, hanarowa/src/app/mypage/password/page.tsx
Datepicker 랑 birth 랑 연동 제대로 안되는것 수정했습니다
전화번호랑 생일 둘 중에 하나만 바꿔도 바로 요청 갈 수 있게 했습니다
=> Fix: mypage/info 수정

hanarowa/src/app/facility/page.tsx, hanarowa/src/middleware.ts
시설 예약 이동 커밋 누락 재업로드했어요
왜 자꾸 누락될까요..
=> Fix: 시설 예약 이동 커밋 누락 재업로드

hanarowa/src/components/facility/ReservationSummary.tsx, hanarowa/src/hooks/useLessonEdit.ts
=> Fix: facility qa 수정

hanarowa/src/app/lesson/create/page.tsx, hanarowa/src/utils/numberInput.ts
=> Fix:  Lesson fee

hanarowa/pnpm-lock.yaml, hanarowa/src/app/ai/page.tsx, hanarowa/src/app/facility/[facilityId]/page.tsx, hanarowa/src/app/lesson/[lessonId]/page.tsx, hanarowa/src/app/lesson/create/page.tsx, hanarowa/src/app/reservation/lesson/page.tsx, hanarowa/src/components/atoms/buttons/GoBackButton.tsx, hanarowa/src/components/atoms/headers/Header.tsx, hanarowa/src/components/facility/FacilityCard.tsx, hanarowa/src/components/facility/FacilityImageCarousel.tsx, hanarowa/src/components/lesson/LessonCard.tsx, hanarowa/src/types/api.ts, hanarowa/src/utils/imageUtils.ts, hanarowa/src/utils/numberInput.ts, hanarowa/src/utils/utils.ts
=> Refactor: 기본이미지 추가, backURL

hanarowa/src/app/reservation/lesson/page.tsx
=> Fix: 내역 없을때 메시지 수정

hanarowa/src/apis/branch/useGetBranch.ts, hanarowa/src/apis/facility/useGetFacilityDetail.ts, hanarowa/src/apis/member/useGetMemberInfo.ts, hanarowa/src/app/facility/branch/[branchId]/page.tsx, hanarowa/src/components/atoms/DatePicker.tsx, hanarowa/src/components/atoms/MemberCard.tsx, hanarowa/src/components/facility/AdminFacilitySection.tsx
=> Refactor: QA 및 코드 리팩토링

hanarowa/src/components/lesson/LessonCard.tsx
=> Fix: lesson card 수강료 수정

hanarowa/src/app/reservation/lesson/page.tsx, hanarowa/src/components/atoms/dropdown/StatusDropdown.tsx, hanarowa/src/components/lesson/LessonReservationCard.tsx
1. 필터(승인,대기,반려 ) 추가
2. LessonReservationCard 컴포넌트 수정
=> Fix: reservation/lesson 페이지 대폭 수정

hanarowa/src/app/admin/lesson/create/page.tsx, hanarowa/src/app/admin/lesson/manage/[id]/page.tsx, hanarowa/src/app/lesson/create/page.tsx, hanarowa/src/components/lesson/LessonEditFormFields.tsx, hanarowa/src/components/lesson/LessonFormFields.tsx, hanarowa/src/components/lesson/MultiDaySelector.tsx, hanarowa/src/components/lesson/index.ts, hanarowa/src/constants/index.ts, hanarowa/src/constants/lesson-options.ts, hanarowa/src/hooks/index.ts, hanarowa/src/hooks/useLessonEdit.ts, hanarowa/src/hooks/useLessonForm.ts, hanarowa/src/types/api.ts, hanarowa/src/types/lesson.ts
1. 강좌 생성, 관리자 강좌 생성, 관리자 강좌 수정 페이지 리펙토링
2. 요일 선택하는 부분 개발
1. 더 작게는 리펙토링 하려면 오히려 코드들이 흩어져서 별로일것 같아요 ㅠ
=> Refactor: LessonCreate

hanarowa/src/apis/serverClient.ts, hanarowa/src/app/auth/refresh/page.tsx
=> Fix: 토큰 재발급 로직 수정

hanarowa/src/app/admin/member/page.tsx
=> Fix: admin memberlist 수정
